services:
  postgres:
    image: postgres:18
    container_name: spring-boot-jwt-postgres
    environment:
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53cret
      POSTGRES_DB: db_security
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yu71" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
